name = "chrobot"
version = "3.0.4"

description = "A browser automation tool and interface to the Chrome DevTools Protocol."
licences = ["MIT"]
repository = { type = "github", user = "JonasGruenwald", repo = "chrobot" }
links = []

[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.49.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_httpc = ">= 4.1.0 and < 6.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
spinner = ">= 1.1.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
justin_fork = { path = "./vendor/justin_fork" }
birdie = ">= 1.1.8 and < 2.0.0"
mist = ">= 4.0.7 and < 6.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
